// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCurrencyApp.Data;

namespace MyCurrencyApp.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20201020052337_update-models-5")]
    partial class updatemodels5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyCurrencyApp.Data.Models.Rate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Currencyid")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataRate")
                        .HasColumnType("datetime2");

                    b.Property<int>("nominal")
                        .HasColumnType("int");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("Currencyid");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("MyCurrencyApp.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numCode")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("MyCurrencyApp.Data.Models.Rate", b =>
                {
                    b.HasOne("MyCurrencyApp.Models.Currency", null)
                        .WithMany("rates")
                        .HasForeignKey("Currencyid");
                });
#pragma warning restore 612, 618
        }
    }
}
